<link rel="stylesheet" href="/css/card.css">
<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

<div class="card">
    <div class="container">
        <div class="image module"></div>
        <h5 class="card-title centered">Web Developer</h5>
    </div>

  <div class="card-body">
    <p class=""><i class="fas fa-clock"></i> 12 horas/semana</p>
    <p class=""> <i class="fas fa-dollar-sign"></i> R$: 200,00</p>
    <p class=""> <b>3</b> dias até o vencimento</p>
    <div class="badges align-right text-right">
        <a href="#" class="badge badge-pill ">Informática</a>
        <a href="#" class="badge badge-pill ">Eletrônica</a>
        <a href="#" class="badge badge-pill ">Automação Industrial</a>
    </div>
  </div>
</div>
