
<link rel="stylesheet" href="css/nav.css">
<script src="script/nav.js" type="text/javascript"></script>

<div id="navBar" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"> <= </a>
    <div class="content">
        <img id="userImg" width="100%" src="assets/profile.jpg" alt="">
        <h1 class="" id="userName" >David Bowie</h1>

        <ul class="list-group" >
            <li><a class="nav-item list-grou-item" href="#">Editar Perfil</a></li>
            <li><a class="nav-item list-grou-item" href="#">Vagas</a></li>
            <li><a class="nav-item list-grou-item" href="#">Convidar Coordenador</a></li>
            <li><a class="nav-item list-grou-item" href="#">Candidatos Pendentes</a></li>
        </ul>
    </div>


</div>
<span onclick="openNav()">-></span>
