
<link rel="stylesheet" href="css/nav.css">
<script src="script/nav.js" type="text/javascript"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<div id="navBar" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"> <= </a>
    <div class="">
        <img id="userImg" class="px-4 " width="100%" src="assets/profile.jpg" alt="">
        <h1 id="userName" class="pl-4">David Bowie</h1>

        <ul class="list-group" >
            <li class="element"><a class="pl-4" href="#">Editar Perfil</a></li>
            <li class="element"><a class="pl-4" href="#">Vagas</a></li>
            <li class="element"><a class="pl-4" href="#">Convidar Coordenador</a></li>
            <li class="element"><a class="pl-4" href="#">Candidatos Pendentes</a></li>
        </ul>
        <a id="logoff" class="pl-4 element" href="#">Sair</a>
        <h1 id="creator" class="sticky-bottom">Made with <i class="fa fa-coffee"></i> and <i class="fas fa-heart"></i> by Rita</h1>
    </div>
</div>
