<link rel="stylesheet" href="/css/card.css">
<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

<div class="card" style="width: 18rem;">
    <div class="container" width="100%">
        <div class="image3 module"></div>
        <h5 class="card-title centered">Monitoramento de um circuito integrado </h5>
    </div>

  <div class="card-body">
    <p class=""><i class="fas fa-clock"></i> 10 horas/semana</p>
    <p class=""><i class="fas fa-dollar-sign"></i> R$: 150,00</p>
    <p class=""> <b>12</b> dias até o vencimento</p>
    <div class="badges align-right text-right">
        <a href="#" class="badge badge-pill">Eletrônica</a>
        <a href="#" class="badge badge-pill">Automação Industrial</a>
    </div>
  </div>
</div>
