<link rel="stylesheet" href="/css/card.css">
<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

<div class="card" style="width: 18rem;">
    <div class="container" width="100%">
        <div class="image2 module"></div>
        <h5 class="card-title centered">Técnico em Química</h5>
    </div>

  <div class="card-body">
    <p class=""><i class="fas fa-clock"></i> 16 horas/semana</p>
    <p class=""><i class="fas fa-dollar-sign"></i> R$: 100,00</p>
    <p class=""> <b>20</b> dias até o vencimento</p>
    <div class="badges align-right text-right">
        <a href="#" class="badge badge-pill">Química</a>
        <a href="#" class="badge badge-pill">Análises Clínicas</a>
    </div>
  </div>
</div>
