
<link rel="stylesheet" href="../css/nav.css">
<script src="../script/nav.js" type="text/javascript"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Lato|Montserrat|Pacifico|Poor+Story|Shadows+Into+Light" rel="stylesheet">


<div id="navBar" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><i class="fas fa-times"></i></a>
    <div class="">
        <div class="borda offset-1 col-10">
            <div class="circle ">
                <img id="userImg" class="" width="200%" src="../assets/profile.jpg" alt="">
            </div>
        </div>

        <h1 id="userName" class="pt-3 text-center">David Bowie</h1>
        <h3 id="userCourse" class="pt-1 text-center">Análises Clínicas</h3>

        <ul class="list-group" >
            <li class="element"><a class="pl-4" href="#">Editar Perfil</a></li>
            <li class="element"><a class="pl-4" href="#">Vagas</a></li>
            <li class="element"><a class="pl-4" href="#">Convidar Coordenador</a></li>
            <li class="element"><a class="pl-4" href="#">Candidatos Pendentes</a></li>
        </ul>

        <a id="logoff" class="pl-4 text-center sticky-bottom" href="#">Sair</a>

    </div>
</div>
